### ISSUE TITLE
[Feature] Console button

### ISSUE THREAD

**Issue by barbiehunter** [cjrose/staticHUD#1]
Idk what i should describe, just add a Console button Please for people they dont have it as bind (like me) :/

**Comment by cjrose** [comment]
I'll add this to the todo list. Due to no more space in the menu itself, it will probably be an simple small square with an image you can click next to the existing twitch and contract buttons

**Comment by cjrose** [comment]
Added in Beta [9.16.2020](../commit/4dc6c9a3965bab8abf5bd0a21dd7e2da0cb1ba21)
